version: "2"
services:
  amrs:
    container_name: ampath_openmrs2.6.0
    image: erugut/ampath-ioms:openmrs-2.6.0
    env_file: main.env
    volumes:
      - /media/data/amrs_prod/test:/root/.OpenMRS
      #- /opt/amrs/data:/root/.OpenMRS
    restart: unless-stopped
    # deploy:
    #   mode: replicated
    #   replicas: 1
    #   placement:
    #     constraints:
    #      - node.hostname == upgrade1
    ports:
      - 8082:8080
